# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "zohoho"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["KentonWhite"]
  s.date = "2013-12-02"
  s.description = "Simple interface to zoho api"
  s.email = "jkentonwhite@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "lib/zohoho.rb",
    "lib/zohoho/authentication.rb",
    "lib/zohoho/connection.rb",
    "lib/zohoho/crm.rb",
    "spec/authentication_spec.rb",
    "spec/connection_spec.rb",
    "spec/crm_spec.rb",
    "spec/fixtures/vcr_cassettes/authentication/call.yml",
    "spec/fixtures/vcr_cassettes/connection/call.yml",
    "spec/fixtures/vcr_cassettes/crm/add_contact.yml",
    "spec/fixtures/vcr_cassettes/crm/contact.yml",
    "spec/fixtures/vcr_cassettes/crm/contact_single.yml",
    "spec/fixtures/vcr_cassettes/crm/delete_lead.yml",
    "spec/fixtures/vcr_cassettes/crm/generate_token.yml",
    "spec/fixtures/vcr_cassettes/crm/note.yml",
    "spec/spec_helper.rb",
    "zohoho.gemspec"
  ]
  s.homepage = "http://github.com/kwhite/zohoho"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Simple interface to zoho api"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.8.0"])
      s.add_runtime_dependency(%q<xml-simple>, ["~> 1.1.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, ["~> 1.3.0"])
      s.add_development_dependency(%q<vcr>, ["~> 1.11.3"])
      s.add_development_dependency(%q<mocha>, ["~> 0.10.5"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.8.0"])
      s.add_dependency(%q<xml-simple>, ["~> 1.1.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<fakeweb>, ["~> 1.3.0"])
      s.add_dependency(%q<vcr>, ["~> 1.11.3"])
      s.add_dependency(%q<mocha>, ["~> 0.10.5"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.8.0"])
    s.add_dependency(%q<xml-simple>, ["~> 1.1.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<fakeweb>, ["~> 1.3.0"])
    s.add_dependency(%q<vcr>, ["~> 1.11.3"])
    s.add_dependency(%q<mocha>, ["~> 0.10.5"])
  end
end

